AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MyInstance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0e2c8ccd4e0222685
      IamInstanceProfile: LabInstanceProfile
