AWSTemplateFormatVersion: '2010-09-09'
Description: 'Infraestructura STF corregida v2'

Resources:
  ServidorDevOps:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: t2.micro
      ImageId: ami-080e1f13689e07408 
      IamInstanceProfile: LabInstanceProfile
      Tags:
        - Key: Name
          Value: Servidor-STF-Alejandro

  BucketDatos:
    Type: 'AWS::S3::Bucket'
    Properties:
      # He cambiado el nombre por uno mas robusto
      BucketName: !Sub 'stf-proyecto-devops-ale-data'
