AWSTemplateFormatVersion: '2010-09-09'
Description: 'Infraestructura STF corregida'

Resources:
  ServidorDevOps:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: t2.micro
      # AMI estándar de Ubuntu 22.04 en us-east-1
      ImageId: ami-080e1f13689e07408 
      IamInstanceProfile: LabInstanceProfile
      Tags:
        - Key: Name
          Value: Servidor-STF-Alejandro

  BucketDatos:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub 'stf-datos-proyecto-'
